name: CI

on:
  pull_request:
    branches: [ "develop-main" ]
  push:
    branches: [ "develop-main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Javaをセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Mavenでビルド＆テスト
        run: mvn clean verify -B