name: CD

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: コードをチェックアウト
              uses: actions/checkout@v4

            - name: Javaをセットアップ
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "21"

            - name: アプリをビルド
              run: mvn clean package -DskipTests

            - name: 秘密鍵を保存
              run: |
                  echo "${{ secrets.SSH_KEY }}" > private_key
                  chmod 600 private_key

            - name: GCEにjarファイルをアップロード
              run: |
                  scp -i private_key -o StrictHostKeyChecking=no \
                    target/*.jar ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }}:/home/${{ secrets.GCE_USER }}/app.jar

            - name: GCEにcredentials.jsonをアップロード
              run: |
                  echo "${{ secrets.GCP_CREDENTIALS_JSON_BASE64 }}" | base64 -d > credentials.json
                  scp -i private_key -o StrictHostKeyChecking=no \
                    credentials.json ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }}:/home/${{ secrets.GCE_USER }}/credentials.json
                  rm credentials.json

            - name: GCEでアプリを再起動
              run: |
                  ssh -i private_key -o StrictHostKeyChecking=no \
                    ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << EOF
                    pkill -f 'java -jar' || true
                    
                    export GOOGLE_APPLICATION_CREDENTIALS=/home/${{ secrets.GCE_USER }}/credentials.json
                    export DB_URL=\$(gcloud secrets versions access latest --secret=DB_URL)
                    export DB_USERNAME=\$(gcloud secrets versions access latest --secret=DB_USERNAME)
                    export DB_PASSWORD=\$(gcloud secrets versions access latest --secret=DB_PASSWORD)
                    export API_KEY=\$(gcloud secrets versions access latest --secret=API_KEY)
                    export GEMINI_API_KEY=\$(gcloud secrets versions access latest --secret=GEMINI_API_KEY)
                    export EMAIL_ADDRESS=\$(gcloud secrets versions access latest --secret=EMAIL_ADDRESS)
                    export EMAIL_PASSWORD=\$(gcloud secrets versions access latest --secret=EMAIL_PASSWORD)
                    nohup java -jar /home/${{ secrets.GCE_USER }}/app.jar > app.log 2>&1 &
                    
                    rm /home/${{ secrets.GCE_USER }}/credentials.json
                  EOF
